inherit_from:
  - .rubocop-shared.yml

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/**/*
    - test/dummy/db/schema.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*
    - config/routes.rb
    - hackathon_manager.gemspec
