rules:
    indentation:
        - 2
        - size: 4
    no-misspelled-properties:
        - 1
        - 'extra-properties':
            - 'gap'
    property-sort-order:
        - 0
    single-line-per-selector:
        - 0
