rules:
    indentation:
        - 2
        - size: 4
    no-misspelled-properties:
        - 1
        - 'extra-properties':
            - 'gap'
    property-sort-order:
        - 0
    single-line-per-selector:
        - 0
    no-transition-all: 0
    hex-notation:
        - 1
        - style: uppercase
    quotes:
        - 1
        - style: double
    clean-import-paths:
        -0

