language: ruby
cache: bundler
sudo: false
bundler_args: --path vendor --local --without development
env:
  - DATABASE_URL="mysql2://travis@localhost/myapp_test"
before_script:
  - mysql -u root -e "CREATE DATABASE myapp_test;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON myapp_test.* TO 'travis'@'%';";
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
script:
  - bin/rails db:migrate
  - RUN_COVERAGE=travis bin/rails test
  - bin/rails coverage:report
addons:
  code_climate:
    repo_token: 702251f0d6eb1f569078a27c4ae3366b1e48c4c6d7e4dd3ae0ca3583fd2bc8db
