# config/app.yml for rails-settings-cached
defaults: &defaults

  # Logic config
  registration_is_open: true
  event_is_over: false
  last_day_to_apply: <%= Date.new(2000, 1, 1) %>
  event_start_date: <%= Date.new(2000, 1, 1) %>
  auto_late_waitlist: false

  # Content config
  name: HackFoo
  logo_asset: "" # (optional)
  favicon_asset: "" # (optional)
  agreement_pdf_asset: agreement.pdf
  email_from: '"HackFoo" <noreply@example.com>'
  default_page_title: HackFoo - Jan 1-2, 2017

  disabled_fields: "" # (optional) why_attend,foo_bar
  disclaimer: "" # Message that appears before signing up & applying. Supports markdown.
  thanks_for_applying: "" # Message that appears after completing an application. Supports markdown.
  thanks_for_rsvp: "" # Message that appears after RSVP'ing as attending. Supports markdown.
  bus_captain_notes: "" # Message that appers on the bus captain's bus list page. Supports markdown.

development:
  <<: *defaults

test:
  <<: *defaults
  last_day_to_apply: <%= 2.months.from_now %>

production:
  <<: *defaults
