version: '3'

services:
  docusaurus:
    build:
      context: ../
      dockerfile: Dockerfile-website
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ../docs:/app/docs
      - ./core:/app/website/core
      - ./i18n:/app/website/i18n
      - ./pages:/app/website/pages
      - ./static:/app/website/static
      - ./sidebars.json:/app/website/sidebars.json
      - ./siteConfig.js:/app/website/siteConfig.js
    working_dir: /app/website
